export const ADD_ARTICLE = "ADD_ARTICLE";

// pokemon list
export const ADD_POKEMON_TO_LIST = "ADD_POKEMON_TO_LIST";
export const REMOVE_POKEMON_TO_LIST = "REMOVE_POKEMON_TO_LIST";

// pokemon lineup
export const ADD_POKEMON_TO_LINEUP = "ADD_POKEMON_TO_LINEUP";
export const REMOVE_POKEMON_TO_LINEUP = "ADD_POKEMON_TO_LINEUP";
